give @s traffic:road_signal_wand 1
give @s traffic:ped_signal_wand 1
give @s traffic:yellow_line_wand 1
give @s traffic:yellow_corner_wand 1
give @s traffic:white_corner_wand 1
give @s traffic:white_corner_side_wand 1
give @s traffic:white_side_left_wand 1
give @s traffic:white_side_right_wand 1
give @s traffic:white_line_side_l_wand 1
give @s traffic:white_line_side_r_wand 1
give @s traffic:crossing_ahead_wand 1
give @s traffic:controller_wand 1
give @s traffic:group_wand 1
give @s traffic:remove_wand 1
give @s traffic:gos_wand 1
give @s traffic:gos_tr_wand 1
give @s traffic:tl_noti_wand 1
give @s traffic:tr_noti_wand 1
give @s traffic:gos_tl_wand 1
give @s traffic:tr_wand 1
give @s traffic:tl_wand 1
give @s traffic:yellowline2_wand 1
give @s traffic:stop_line_wand 1
give @s traffic:cross_small_wand 1
give @s traffic:cross_big_wand 1
give @s traffic:cross_small_m_wand 1
give @s traffic:cross_big_m_wand 1
give @s traffic:guideline_wand 1
tellraw @s {"rawtext":[{"text":"Traffic tools granted. Placement wands place on the top face, the controller wand opens one controller UI, the group wand opens group/link UI, the remove wand deletes one traffic entity on use and deletes connected straight-line runs on left-hit, the road signal wand can left-hit a road signal to change its model, the guideline wand can left-hit a guideline to change its size, the stop line wand can left-hit a stop line to step its frame, and particle diagonal tools are available via /function traffic/give_particle_tools."}]}
